gestures {
    workspace_swipe = true
    workspace_swipe_cancel_ratio = 0.08
}

plugin {
    touch_gestures {
        sensitivity = 5.0

        workspace_swipe_fingers = 2

        long_press_delay = 250
        resize_on_border_long_press = true
        edge_margin = 64

        hyprgrass-bind = , edge:d:u, exec, $menu
        hyprgrass-bind = , edge:u:d, exec, $lock
        hyprgrass-bind = , edge:u:l, exec, $ss
        hyprgrass-bind = , edge:d:r, exec, $clip
        hyprgrass-bind = , edge:l:r, exec, ydotool key 56:1 105:1 105:0 56:0
        hyprgrass-bind = , edge:r:l, exec, ydotool key 56:1 105:1 105:0 56:0

        hyprgrass-bind = , tap:3, exec, $terminal

        hyprgrass-bind = , swipe:4:d, togglefloating
        hyprgrass-bind = , swipe:4:u, fullscreen
        hyprgrass-bind = , swipe:3:d, killactive
        hyprgrass-bind = , swipe:3:u, exec, /home/me/.config/hypr/toggle-wvkbd.sh

        hyprgrass-bindm = , longpress:2, movewindow
        hyprgrass-bindm = , longpress:3, resizewindow
    }
}
