#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HYPR_COLORS_FILE="$SCRIPT_DIR/hyprland-wal.conf"
LOG_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/wal-apply-theme.log"
DEFAULT_WALLPAPER_DIR="$HOME/wpps"
WALLPAPER_PATH="${1:-${WALLPAPER_PATH:-}}"
BRIGHTNESS_BOOST="${BRIGHTNESS_BOOST:-48}"
INACTIVE_DARKEN="${INACTIVE_DARKEN:-36}"

brighten_hex() {
  local hex="${1#\#}"
  local boost="$2"
  local r g b

  r=$((16#${hex:0:2}))
  g=$((16#${hex:2:2}))
  b=$((16#${hex:4:2}))

  r=$((r + boost))
  g=$((g + boost))
  b=$((b + boost))

  (( r > 255 )) && r=255
  (( g > 255 )) && g=255
  (( b > 255 )) && b=255

  printf '#%02x%02x%02x' "$r" "$g" "$b"
}

darken_hex() {
  local hex="${1#\#}"
  local amount="$2"
  local r g b

  r=$((16#${hex:0:2}))
  g=$((16#${hex:2:2}))
  b=$((16#${hex:4:2}))

  r=$((r - amount))
  g=$((g - amount))
  b=$((b - amount))

  (( r < 0 )) && r=0
  (( g < 0 )) && g=0
  (( b < 0 )) && b=0

  printf '#%02x%02x%02x' "$r" "$g" "$b"
}

if ! command -v wal >/dev/null 2>&1; then
  echo "error: 'wal' is required" >&2
  exit 1
fi

if [ -z "$WALLPAPER_PATH" ]; then
  WALLPAPER_PATH="$(find "$DEFAULT_WALLPAPER_DIR" -maxdepth 1 -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' -o -iname '*.jxl' \) | sort | head -n 1)"
fi

if [ -z "$WALLPAPER_PATH" ] || [ ! -f "$WALLPAPER_PATH" ]; then
  printf '%s error wallpaper not found: %s\n' "$(date '+%F %T')" "${WALLPAPER_PATH:-<empty>}" >> "$LOG_FILE"
  echo "error: wallpaper not found: ${WALLPAPER_PATH:-<empty>}" >&2
  exit 1
fi

if ! wal -i "$WALLPAPER_PATH" -n >/dev/null 2>&1; then
  printf '%s error wal failed for: %s\n' "$(date '+%F %T')" "$WALLPAPER_PATH" >> "$LOG_FILE"
  echo "error: wal failed for $WALLPAPER_PATH" >&2
  exit 1
fi

CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/wal"
COLORS_SH="$CACHE_DIR/colors.sh"

if [ ! -f "$COLORS_SH" ]; then
  printf '%s error missing colors.sh after wal for: %s\n' "$(date '+%F %T')" "$WALLPAPER_PATH" >> "$LOG_FILE"
  echo "error: wal did not generate $COLORS_SH" >&2
  exit 1
fi

# shellcheck disable=SC1090
set +u
source "$COLORS_SH"
set -u

active_start="$(brighten_hex "$color12" "$BRIGHTNESS_BOOST")"
active_end="$(brighten_hex "$color13" "$BRIGHTNESS_BOOST")"
inactive="$(darken_hex "$color8" "$INACTIVE_DARKEN")"
group="$(brighten_hex "$color14" "$BRIGHTNESS_BOOST")"
group_locked="$(brighten_hex "$color9" "$BRIGHTNESS_BOOST")"

ACTIVE_BORDER="rgb(${active_start#\#}) rgb(${active_end#\#})"
INACTIVE_BORDER="rgb(${inactive#\#})"
GROUP_BORDER="rgb(${group#\#})"
GROUP_BORDER_LOCKED="rgb(${group_locked#\#})"

cat > "$HYPR_COLORS_FILE" <<THEME
# Auto-generated by wal-apply-theme.sh
\$active_border = $ACTIVE_BORDER
\$inactive_border = $INACTIVE_BORDER
\$group_border = $GROUP_BORDER
\$group_border_locked = $GROUP_BORDER_LOCKED
THEME

if command -v hyprctl >/dev/null 2>&1; then
  hyprctl --batch \
    "keyword general:col.active_border $ACTIVE_BORDER ; keyword general:col.inactive_border $INACTIVE_BORDER" \
    >/dev/null 2>&1 || true
fi

printf '%s applied %s -> %s | %s\n' "$(date '+%F %T')" "$WALLPAPER_PATH" "$ACTIVE_BORDER" "$INACTIVE_BORDER" >> "$LOG_FILE"

if [ -x "$SCRIPT_DIR/apply-cava-sdl-theme.sh" ]; then
  "$SCRIPT_DIR/apply-cava-sdl-theme.sh" || true
fi

if [ -x "$SCRIPT_DIR/apply-eww-cava-theme.sh" ]; then
  "$SCRIPT_DIR/apply-eww-cava-theme.sh" || true
fi

if [ -z "${SKIP_CAVA_BG_THEME:-}" ] && [ -x "$SCRIPT_DIR/apply-cava-bg-theme.sh" ]; then
  "$SCRIPT_DIR/apply-cava-bg-theme.sh" || true
fi

# if [ -x "$SCRIPT_DIR/apply-glava-theme.sh" ]; then
#   "$SCRIPT_DIR/apply-glava-theme.sh" || true
# fi

echo "applied wal theme from: $WALLPAPER_PATH"
echo "generated: $HYPR_COLORS_FILE"
